# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_activity', '0002_auto_20171021_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
