# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_activity', '0004_auto_20171022_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='volunteer', max_length=10),
        ),
    ]
