# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_activity', '0005_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.CharField(max_length=10)),
                ('event_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer_activity.Event')),
                ('user_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer_activity.User')),
            ],
        ),
    ]
