# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_activity', '0006_userevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='event_name',
        ),
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
