# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_activity', '0009_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='updated_date',
        ),
    ]
