# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_activity', '0010_remove_profile_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.CharField(max_length=100),
        ),
    ]
